# Generated by Django 6.0.3 on 2026-04-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Done', 'completed'), ('Not Done', 'not completed')], default='Not Done', max_length=10),
        ),
    ]
